### ISSUE TITLE
Getting Connection Refused

### ISSUE THREAD

**Issue by nexusguy59** [taosnet/virt-manager#1]
This is how I started it:
docker run --name cfVirt -p 5903/tcp -p 5903:5903 taosnet/virt-manager
----------
ErrorMsg
12/08/2018 10:57:11
Opening connection failed!
Unable to connect to the server. Error was: No connection could be made because the target machine actively refused it 192.168.1.5:5903
----------

These are already using 5900 to 5902
tcp        0      0 0.0.0.0:5900            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:5901            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:5902            0.0.0.0:*               LISTEN      -

and it looks like 5903 is only availble on ipv6
tcp6       0      0 :::5903                 :::*                    LISTEN

This is what I get when I do a docker ps -a
c138489eaa26        taosnet/virt-manager   "/start.sh xterm -e …"   7 minutes ago       Up 7 minutes        22/tcp, 5901/tcp, 0.0.0.0:5903->5903/tcp, 0.0.0.0:32768->5903/tcp   cfVirt
cfadmin@cfkvmdoc1:~$ docker exec -it c138489eaa26 /bin/sh
sh-4.2# ps -ef | grep virt
root        38    36  0 15:54 pts/0    00:00:00 /usr/bin/python2 /usr/share/virt-manager/virt-manager --no-fork
root        86    78  0 16:02 pts/1    00:00:00 grep virt

What am I doing wrong?

Thanks,

**Comment by tnChris** [comment]
As you can see virt-manager is running as root. root's VNC port is 5901. If you run the docker image with -p 5901 instead of -p 5903, and then connect to 5901 you should be able to connect. If you are already using 5901 on the docker host for something else, you can always do -p 5903:5901.
Thanks!

**Comment by nexusguy59** [comment]
How stupid of me good point you can close this......

**Comment by tnChris** [comment]
Thanks for trying out this image!
